# Generated by Django 3.1.5 on 2021-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
        ('accounts', '0002_auto_20210119_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appreciated_entries',
            field=models.ManyToManyField(blank=True, related_name='appreciated', to='entries.Entry'),
        ),
        migrations.AlterField(
            model_name='user',
            name='changed_perception_entries',
            field=models.ManyToManyField(blank=True, related_name='changed_perc', to='entries.Entry'),
        ),
    ]
