# Generated by Django 3.1.5 on 2021-01-27 12:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=accounts.models.upload_image_location),
        ),
    ]
